require('user.settings')
require('user.keymaps')
require('user.plugins')
require('user.lsp')	
require('user.colors')
require('user.telescope')
require('user.treesitter')
require('user.nvimtree')
require('user.cmp') 

